####
#### Author: Marcello DeSales (@mdesales)
####
name: server-docker-image-build

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      # Long-term gitflow branches
      - develop
      - main

      # Short-term gitflow branches
      - feature/**
      - bugfix/**
      - hotfix/**

      # the list of AI-created branches
      - dependabot/**
      - codex/**

  push:
    tags:
      # Releases could have the build of the image
      - "v*"

jobs:
  docker-devsecops:
    name: 🐳 docker
    uses: marcellodesales/vionix/.github/workflows/workflow-build-docker-image.yaml@oss/main-image-container
    with:
      github-actions-runner: ubuntu-latest
      docker-compose-context: .
      docker-compose-file: docker-compose.yaml
      docker-compose-service: mcp-gateway
      check-fail-on-yaml-json-lint-error: false
      check-allow-multiple-yaml-documents: true
      docker-submit-sbom: true
    secrets:
      # Docker registry username defaults to the reponame for dockerhub authentication, established in docker-compose.yaml
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
    permissions:
      # Actions values
      actions: read
      # Authenticated GITHUB_TOKENS to clone repo
      id-token: write
      contents: write
      # Set the deployment once the image is pushed
      deployments: write
      # Write comments to Pull Requests
      pull-requests: write
      # Submit security events
      security-events: read
      # Submit attestations: https://docs.docker.com/build/metadata/attestations/#attestation-manifest-format
      # This is only available for public repos https://docs.github.com/en/rest/repos/repos#create-an-attestation
      attestations: write
      packages: write
